# Generated by Django 5.1.3 on 2026-07-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('educational_qualification', models.CharField(choices=[('Intermediate', 'Intermediate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('Other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_id', models.CharField(blank=True, max_length=255)),
                ('instagram_id', models.CharField(blank=True, max_length=255)),
                ('utr_number', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
