# Generated by Django 5.1.3 on 2026-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='aadhaar_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.CharField(choices=[('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35')], default='18', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Entrepreneur', 'Entrepreneur'), ('Working Professional', 'Working Professional'), ('Government Employee', 'Government Employee'), ('Teacher / Faculty', 'Teacher / Faculty'), ('Doctor', 'Doctor'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Farmer', 'Farmer'), ('Business Owner', 'Business Owner'), ('Social Worker / NGO', 'Social Worker / NGO'), ('Political Worker', 'Political Worker'), ('Other', 'Other')], default='student', max_length=50),
            preserve_default=False,
        ),
    ]
